# DEPENDS github.sh

# Install dotfiles.
cd ~
git init
git remote add origin git@github.com:banool/dotfiles.git
git pull origin master

# Remove unneeded dotfiles for an Ubuntu server.
for i in ".hushlogin" ".atom" ".gitignore"; do
    rm -rf "$i"
done

# Remove the .git directory generated by cloning the dotfiles.
rm -rf .git
